- name: Create Parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Create Parameters
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
      loop:
        - {name: "dev.cart.REDIS_HOST", value: "redis-dev.awsctr.online" }
        - {name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.awsctr.online" }
        - {name: "dev.catalogue.MONGO", value: "true" }
       # - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.awsctr.online:27017/catalogue" }
        - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.awsctr.online:27017/catalogue" }
        - {name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.awsctr.online:80/" }
        - {name: "dev.frontend.CART_URL", value: "http://cart-dev.awsctr.online:80/" }
        - {name: "dev.frontend.USER_URL", value: "http://user-dev.awsctr.online:80/" }
        - {name: "dev.frontend.PAYMENT_URL", value: "http://payment-dev.awsctr.online:80/" }
        - {name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.awsctr.online:80/" }
        - {name: "dev.payment.CART_HOST", value: "cart-dev.awsctr.online" }
        - {name: "dev.payment.USER_HOST", value: "user-dev.awsctr.online" }
        - {name: "dev.payment.CART_PORT", value: "80" }
        - {name: "dev.payment.USER_PORT", value: "80" }
        - {name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.awsctr.online" }
        - {name: "dev.dispatch.AMQP_HOST", value: "rabbitmq-dev.awsctr.online" }
        - {name: "dev.payment.AMQP_USER", value: "roboshop" }
        - {name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.awsctr.online:80" }
        - {name: "dev.shipping.DB_HOST", value: "mysql-dev.awsctr.online" }
        - {name: "dev.user.MONGO", value: "true" }
        - {name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.awsctr.online:27017/users" }
        - {name: "dev.user.REDIS_HOST", value: "redis-dev.awsctr.online" }

## prod
        - {name: "prod.cart.REDIS_HOST", value: "redis-prod.awsctr.online" }
        - {name: "prod.cart.CATALOGUE_HOST", value: "catalogue-prod.awsctr.online" }
        - {name: "prod.catalogue.MONGO", value: "true" }
        # - {name: "prod.catalogue.MONGO_URL", value: "mongodb://mongodb-prod.awsctr.online:27017/catalogue" }
        - {name: "prod.catalogue.MONGO_URL", value: "mongodb://mongodb-prod.awsctr.online:27017/catalogue" }
        - {name: "prod.frontend.CATALOGUE_URL", value: "http://catalogue-prod.awsctr.online:80/" }
        - {name: "prod.frontend.CART_URL", value: "http://cart-prod.awsctr.online:80/" }
        - {name: "prod.frontend.USER_URL", value: "http://user-prod.awsctr.online:80/" }
        - {name: "prod.frontend.PAYMENT_URL", value: "http://payment-prod.awsctr.online:80/" }
        - {name: "prod.frontend.SHIPPING_URL", value: "http://shipping-prod.awsctr.online:80/" }
        - {name: "prod.payment.CART_HOST", value: "cart-prod.awsctr.online" }
        - {name: "prod.payment.USER_HOST", value: "user-prod.awsctr.online" }
        - {name: "prod.payment.CART_PORT", value: "80" }
        - {name: "prod.payment.USER_PORT", value: "80" }
        - {name: "prod.payment.AMQP_HOST", value: "rabbitmq-prod.awsctr.online" }
        - {name: "prod.dispatch.AMQP_HOST", value: "rabbitmq-prod.awsctr.online" }
        - {name: "prod.payment.AMQP_USER", value: "roboshop" }
        - {name: "prod.shipping.CART_ENDPOINT", value: "cart-prod.awsctr.online:80" }
        - {name: "prod.shipping.DB_HOST", value: "mysql-prod.awsctr.online" }
        - {name: "prod.user.MONGO", value: "true" }
        - {name: "prod.user.MONGO_URL", value: "mongodb://mongodb-prod.awsctr.online:27017/users" }
        - {name: "prod.user.REDIS_HOST", value: "redis-prod.awsctr.online" }
    ### PASSWORDS SHOULD NEVER BE KEPT IN THESE REPOS, THOSE SHOULD BE CREATED MAUALLY, BUT FOR LAB PURPOSE IAM CREATING HERE
    - name: Create Secrets
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
        string_type: "SecureString"
      loop:
        - {name: "dev.payment.AMQP_PASS", value: "roboshop1234" }
        - { name: "dev.rabbitmq.AMQP_USER", value: "roboshop" }
        - {name: "dev.rabbitmq.AMQP_PASS", value: "roboshop1234" }
        - {name: "dev.mysql.DB_ADMIN_USER", value: "root" }
        - {name: "dev.mysql.DB_ADMIN_PASS", value: "RoboShop@1" }
        - {name: "dev.docdb.DB_ADMIN_USER", value: "admin1" }
        - {name: "dev.docdb.DB_ADMIN_PASS", value: "RoboShop123" }
        - {name: "dev.rds.DB_ADMIN_USER", value: "admin1" }
        - {name: "dev.rds.DB_ADMIN_PASS", value: "RoboShop123" }
        - { name: "dev.rabbitmq.USER", value: "roboshop" }
        - { name: "dev.rabbitmq.PASS", value: "roboshop1234" }
        - { name: "dev.dispatch.AMQP_PASS", value: "roboshop1234" }
        - { name: "dev.dispatch.AMQP_USER", value: "roboshop" }
        - { name: "grafana.api_key", value: "eyJrIjoidUNiUXloNXlveXk1YUxMYjZyZDVjVVVIbjhEUFA2VGgiLCJuIjoiY2xpIiwiaWQiOjF9" }
        - { name: "ses.user", value: "AKIARICXTIURAJ52LUU6" }
        - { name: "ses.pass", value: "BDXleegCYGv1FrvC7VIRsjCvdhIAjCZqyUGStpU3JwG1" }
        - { name: "dev.ssh.USER", value: "centos" }
        - { name: "dev.ssh.PASS", value: "DevOps321" }
# prod
        - {name: "prod.payment.AMQP_PASS", value: "roboshop1234" }
        - { name: "prod.rabbitmq.AMQP_USER", value: "roboshop" }
        - {name: "prod.rabbitmq.AMQP_PASS", value: "roboshop1234" }
        - {name: "prod.mysql.DB_ADMIN_USER", value: "root" }
        - {name: "prod.mysql.DB_ADMIN_PASS", value: "RoboShop@1" }
        - {name: "prod.docdb.DB_ADMIN_USER", value: "admin1" }
        - {name: "prod.docdb.DB_ADMIN_PASS", value: "RoboShop123" }
        - {name: "prod.rds.DB_ADMIN_USER", value: "admin1" }
        - {name: "prod.rds.DB_ADMIN_PASS", value: "RoboShop123" }
        - { name: "prod.rabbitmq.USER", value: "roboshop" }
        - { name: "prod.rabbitmq.PASS", value: "roboshop1234" }
        - { name: "prod.dispatch.AMQP_PASS", value: "roboshop1234" }
        - { name: "prod.dispatch.AMQP_USER", value: "roboshop" }
        - { name: "grafana.api_key", value: "eyJrIjoidUNiUXloNXlveXk1YUxMYjZyZDVjVVVIbjhEUFA2VGgiLCJuIjoiY2xpIiwiaWQiOjF9" }
        - { name: "ses.user", value: "AKIARICXTIURAJ52LUU6" }
        - { name: "ses.pass", value: "BDXleegCYGv1FrvC7VIRsjCvdhIAjCZqyUGStpU3JwG1" }
        - { name: "prod.ssh.USER", value: "centos" }
        - { name: "prod.ssh.PASS", value: "DevOps321" }




