- name: Roboshop Applicartion Deployment
  hosts: all
  become: yes
  serial: 1 # this is (serial) used to deploy 1 server at a time here we have given 2 servers for shipping if we take out serial it will deploy 2 servers at same time (if number of servers is 10 also same method)
  tasks:
    - name: Import deployment file from common tasks
      ansible.builtin.import_role:
        name: common
        tasks_from: deploy

