#source common.sh
#
#print_head "Install Nginx"
#yum install nginx -y &>>${LOG}
#status_check

#print_head "Remove Nginx Old Content"
#rm -rf /usr/share/nginx/html/* &>>${LOG}
#status_check


#print_head "Download Frontend Content"
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${LOG}
#status_check

#cd /usr/share/nginx/html &>>${LOG}

#print_head "Extract Frontend Content"
#unzip /tmp/frontend.zip &>>${LOG}
#status_check

#print_head "Copy RoboShop Nginx Config File"
#cp ${script_location}/files/nginxroboshop.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#status_check

#print_head "Enable Nginx"
#systemctl enable nginx &>>${LOG}
#status_check

#print_head "Start Nginx"
#systemctl restart nginx &>>${LOG}
#status_check

- name: Install the latest version of Apache
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old HTTPD documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a HTTPD Directroy
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
