- name: configure nod JS repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install the latest version of Apache
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: add a application user roboshop
  ansible.builtin.user:
    name: roboshop


- name: Remove old contents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a app Directroy
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: installing node js dependenciesnpm installation.
  npm:
    path: /app
    state: latest

- name: Copying file catalogue.service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: starting catalogue service
  ansible.builtin.systemd:
    state: restarted
    name: catalogue
    enabled: yes
    daemon_reload: true


- name: Copying  mongodb repofile
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  community.mongodb.mongodb_shell:
    login_host: mongodb.kiranprav.link
    file: "/app/schema/catalogue.js"
    idempotent: yes
