- name: Copy Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  vars:
    labels:
      - { tag: "env", label: "environment" }
      - { tag: "Name", label: "name" }

# create record rules for prometheus with the help pf template record-rules.yml
- name: Copy record Rules
  ansible.builtin.template:
    src: record-rules.yml
    dest: /opt/prometheus/record-rules.yml

# create alert rules for prometheus with the use of template alert-rules.yml
- name: alert Rules
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

# create alert rules for prometheus with the use of template alert-rules.yml
- name: alert manager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

# creating grafana dashboard using json code
#- name: make template
#  ansible.builtin.template:
#    src: grafana-template.json
#    dest: /tmp/grafana.json
#    remote_src: yes

#- name: Import Grafana dashboard foo
#  community.grafana.grafana_dashboard:
#    grafana_url: http://172.31.2.56:3000
#    grafana_api_key: "{{ grafana_api_key }}"
#    state: present
#    commit_message: Updated by ansible
#    overwrite: yes
#    path: /tmp/grafana.json