- name: copy prometheus config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  vars:
    - { tag : "env", labels: "environment" }
    - { tag : "env", Name: "name" }

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted