
- name: add a application user roboshop
  ansible.builtin.user:
    name: roboshop


- name: Remove old contents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a app Directroy
  ansible.builtin.file:
    path: /app
    state: directory

#- name: downloading {{component}} App content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: download {{component}}artifact from repository
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_password}}@172.31.12.164:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes
  vars:

    nexus_user: "{{ lookup('aws_ssm', 'nexus.user', region='us-east-1' ) }}"
    nexus_password: "{{ lookup('aws_ssm', 'nexus.password', region='us-east-1' ) }}"



