
- name: add a application user roboshop
  ansible.builtin.user:
    name: roboshop


- name: Remove old contents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a app Directroy
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading {{component}} App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

#- name: donwload artificat from repository
#  ansible.builtin.unarchive:
#    src: http://172.31.2.104:8081/#browse/browse:{{component}}:{{componenet}}-{{app_version}}.zip
#    dest: /app
#    remote_src: yes