- name: stop the application
  ansible.builtin.systemd:
    name: "{{component}}"
    state: stopped

- name: App -prereq will be given here
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: start the application
  ansible.builtin.systemd:
    name: "{{component}}"
    state: started