- name: install python
  ansible.builtin.yum:
    name:
      - python3-PyMySQL
      - mysql
    state: installed

- name: loading mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: 172.31.2.158
    login_user: root
    login_password: "{{root_mysql_password}}"
    vars:
      root_mysql_password: "{{ lookup('aws_ssm', "{{env}}.mysql.DB_ADMIN_PASSWORD", region='us-east-1' ) }}"