- name: install python
  ansible.builtin.yum:
    name: python3-PyMySQL
    state: installed

- name: loading mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql.kiranprav.link
    login_password: "{{root_mysql_password}}"