#PYTHON() {

#print_head "Install Python"
#yum install python36 gcc python3-devel -y &>>${LOG}
#status_check

#APP_PREREQ

#print_head "Download Dependencies"
#cd /app
#pip3.6 install -r requirements.txt  &>>${LOG}
#status_check

#print_head "Update Passwords in Service File"
#sed -i -e "s/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/" ${script_location}/files/${component}.service  &>>${LOG}
#status_check

#SYSTEMD_SETUP


- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel

- name: app-prereq
  ansible.builtin.include_tasks: "app-prereq.yml"


- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: systemd
  ansible.builtin.include_tasks: "systemd.yml"

- name: import schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load
