- name: Copying file {{component}}.service
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: starting catalogue service
  ansible.builtin.systemd:
    state: restarted
    name: "{{component}}"
    enabled: yes
    daemon_reload: true

